Add tasks to collect OVN/OVS logs
rhevm-qe-automation/ovirt-ansible pull request #185
Opened 2022-06-22 09:05 UTC by MosheSheena

This change adds collection of OVN/OVS logs from both Ovirt Engine
and hypervisors
This is elementary in order to analyze failures in these components

2022-06-22 09:06 UTC, MosheSheena commented
@kobihk Hi can you please review?

2022-06-23 11:30 UTC, kobihk requested changes

2022-06-23 11:30 UTC, kobihk commented on roles/ovirt-collect-logs/tasks/hypervisor.yml
> +      dest: "ovs-logs"
same here

2022-06-23 11:49 UTC, kobihk requested changes

2022-06-23 11:49 UTC, kobihk commented on roles/ovirt-collect-logs/tasks/engine.yml
> +          dest: "ovs-logs"
please fix the indentation
```suggestion
    - src: "/var/log/openvswitch"
      dest: "ovs-logs"
```

2022-06-23 11:49 UTC, kobihk commented on roles/ovirt-collect-logs/tasks/hypervisor.yml
> +          dest: "ovs-logs"
same ^^

2022-06-23 15:26 UTC, MosheSheena commented on roles/ovirt-collect-logs/tasks/hypervisor.yml
> +      dest: "ovs-logs"
Same above.
The terms are interchangable

2022-06-23 19:03 UTC, kobihk commented on roles/ovirt-collect-logs/tasks/engine.yml
> +      dest: "ovs-logs"
The question is if one will not overwrite the other one?

2022-06-26 12:24 UTC, MosheSheena commented on roles/ovirt-collect-logs/tasks/engine.yml
> +      dest: "ovs-logs"
Why should one overwrite the other?
On both Engine and hosts you collect logs to two distinct directories.

2022-06-26 12:40 UTC, kobihk approved these changes

2022-06-27 06:30 UTC, MosheSheena commented
@kobihk Do you think CI is stuck?..
If so is there a way to re-trigger it without pushing any other commits?

2022-06-27 10:32 UTC, kobihk commented on roles/ovirt-collect-logs/tasks/engine.yml
> +      dest: "ovs-logs"
yep you are right I missed it

2022-06-27 10:38 UTC, kobihk approved these changes

2022-06-27 10:40 UTC, merged